---

- name: Ensure the include directory exists
  file:
    path: '{{ sudoers__include_directory }}'
    owner: root
    group: root
    mode: 0750
    state: directory

- name: List installed sudoers rules files
  find:
    paths: '{{ sudoers__include_directory }}'
    file_type: file
  register: _sudoers__installed_files

# purge feature

- name: List ansible managed sudoers rules files
  find:
    paths: '{{ sudoers__include_directory }}'
    file_type: file
    contains: '#{{ sudoers__ansible_managed_key }}'
  when: sudoers__purge|bool
  register: _sudoers__managed_files

- name: Remove unknown installed sudoers rules files
  file:
    path: '{{ item }}'
    state: absent
  with_items:
    "{{ _sudoers__installed_files.files|map(attribute='path')
        |difference(_sudoers__managed_files.files|map(attribute='path'))|list }}"
  when: sudoers__purge|bool and item|basename not in ['README']

# configuration

- name: Insert README file into include directory
  copy:
    src: files/README
    dest: '{{ sudoers__include_directory }}/README'
    mode: 0440

- name: Configure the main sudoers file
  template:
    src: sudoers.j2
    dest: '{{ sudoers__config_file }}'
    owner: root
    group: root
    mode: 0440
    validate: 'visudo -cf %s'

- name: Configure sudo rules
  include_tasks: types/sudo_rule.yml
  vars:
    sudoers__sudo_rule: "{{ outer_item.value|combine({'name': outer_item.key}) }}"
  with_dict: '{{ sudoers__rules }}'
  loop_control:
    loop_var: outer_item
