---

- name: Ensure the include directory exists
  file:
    path:  '{{ sudoers__include_dir }}'
    owner: root
    group: root
    mode:  0750
    state: directory

- name: Configure the main sudoers file
  template:
    src:   sudoers.j2
    dest:  '{{ sudoers__config_file }}'
    owner: root
    group: root
    mode:  0440
    validate: 'visudo -cf %s'
