---

- name: Ensure the include directory exists
  file:
    path: '{{ sudoers__include_dir }}'
    owner: root
    group: root
    mode:  0750
    state: directory

- name: List installed sudoers rules files
  find:
    file_type: file
    paths:     '{{ sudoers__include_dir }}'
  register: _sudoers__installed_files
  check_mode: false

- name: Remove unknown installed sudoers rules files
  file:
    path: '{{ item.path }}'
    state: absent
  with_items: "{{ _sudoers__installed_files.files }}"
  when: item.path|basename not in ['README'] and sudoers__purge|bool
  check_mode: "{{ ansible_check_mode if (not sudoers__purge_checkmode|d(false)|bool) else 'yes' }}"

- name: Insert README file into include directory
  copy:
    src: files/README
    dest: '{{ sudoers__include_dir }}/README'
    mode: 0440

- name: Configure the main sudoers file
  template:
    src: sudoers.j2
    dest: '{{ sudoers__config_file }}'
    owner: root
    group: root
    mode: 0440
    validate: 'visudo -cf %s'

- name: Configure sudo rules
  include_tasks: types/sudo_rule
  vars:
    sudoers__sudo_rule: "{{ outer_item.value|combine({'name': outer_item.key}) }}"
  with_dict: '{{ sudoers__rules }}'
  loop_control:
    loop_var: outer_item
