---

- name: Install sudo packages
  package:
    name: '{{ sudoers__packages_names|list }}'
    state: present

- name: Install sudo packages required for sss service
  package:
    name: '{{ sudoers__sss_packages_names|list }}'
    state: present
  when: sudoers__sss|bool
