---
# tasks file for sudoers

- name: Include the OS specific variables
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
        - defaults.yml
      skip: true
  tags: ['always']

- name: Import install tasks
  import_tasks: install.yml
  tags: ['sudoers', 'sudoers-install']

- name: Import configure tasks
  import_tasks: configure.yml
  tags: ['sudoers', 'sudoers-configure']

- name: Optionally include facts tasks
  include_tasks: facts.yml
  when: sudoers__facts|bool
  tags: ['sudoers', 'sudoers-facts']
