---

- name: Check rule prerequisites
  assert:
    that:
      - sudoers__sudo_rule is defined
    msg: sudoers__sudo_rule must be defined with specifications

- name: Ensure include directory exists
  file:
    path:  '{{ sudoers__include_dir }}'
    mode:  0750
    state: directory

- name: 'Create sudoers rule {{ sudoers__sudo_rule.name }}'
  template:
    src:      sudo_rule.j2
    dest:     "{{ sudoers__include_dir }}/{{ sudoers__sudo_rule.name|lower|regex_replace('[^a-z0-9_-]', '_') }}"
    owner:    root
    group:    root
    mode:     0440
    validate: 'visudo -cf %s'
  when: sudoers__sudo_rule.state|d('present') == 'present'

- name: 'Remove sudoers rule {{ sudoers__sudo_rule.name }}'
  file:
    path:  "{{ sudoers__include_dir }}/{{ sudoers__sudo_rule.name|lower|regex_replace('[^a-z0-9_-]', '_') }}"
    state: absent
  when: sudoers__sudo_rule.state|d('present') != 'present'
